# Generated by Django 4.2.6 on 2023-11-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('curso', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('descrição', models.TextField(max_length=255)),
            ],
        ),
    ]
