# Generated by Django 4.2.6 on 2023-11-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meus_cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='status',
            new_name='finalizado',
        ),
    ]
